"""API schemas for the query endpoint."""

from pydantic import BaseModel, Field
from typing import List, Literal

class QueryRequest(BaseModel):
  """Input payload for `POST /api/query`."""

  query: str = Field(..., min_length=1, description="The query to search the knowledge base for")

class ClassificationItem(BaseModel):
  """One source-specific sub-query generated by the router classifier."""

  source: Literal["github","notion","slack"]
  query: str

class QueryResponse(BaseModel):
  """Response payload returned by `POST /api/query`."""

  query: str
  classifications: List[ClassificationItem] = Field(default_factory=list)
  final_answer: str